source: .
destination: ./_site
plugins:     ./_plugins

permalink: /blog/:year/:month/:title

exclude: resources, deploy.sh, deploy_example.sh, Gemfile.lock, Gemfile, readme.md

future: false

url: http://chrisltd.com