# Documentation: https://github.com/mojombo/jekyll/wiki/configuration

url: https://chrisltd.com
permalink: /blog/:year/:month/:title/

source: .
destination: ./_site
plugins_dir:     ./_plugins

future: false # publish posts dated into the future
exclude: [resources, deploy.sh, deploy_example.sh, localtest.sh, Gemfile.lock, Gemfile, readme.md]

markdown: kramdown
highlighter: rouge

# Custom
title: Chris Johnson - Developer in NYC
description: Chris Johnson is a developer in NYC. This is his portfolio and blog.
tagline: Developer in NYC
author: Chris Johnson
feed_url: /blog/feed.xml
feed_title: Chris Johnson's Blog
assets_version: 18 # used to cache bust css and js files
