# Documentation: https://github.com/mojombo/jekyll/wiki/configuration

url: http://chrisltd.com
permalink: /blog/:year/:month/:title

source: .
destination: ./_site
plugins:     ./_plugins

future: false # publish posts dated into the future
exclude: [resources, deploy.sh, deploy_example.sh, localtest.sh, Gemfile.lock, Gemfile, readme.md]

markdown: maruku
pygments: true

# Custom
author: Chris Johnson
feed_url: /blog/feed/
assets_version: 15 # used to cache bust css and js files