import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
};

const tools = [
  { name: 'HTML5', url: 'https://en.wikipedia.org/wiki/HTML5', color: '#df4e28' },
  { name: 'TypeScript', url: 'https://www.typescriptlang.org/', color: '#3178c6' },
  { name: 'React', url: 'https://reactjs.org/', color: '#292929' },
  { name: 'Next.js', url: 'https://nextjs.org/', color: '#171717' },
  { name: 'Tailwind CSS', url: 'https://tailwindcss.com/', color: '#00a6f4' },
  { name: 'Git', url: 'https://git-scm.com/', color: '#e95235' },
  { name: 'Rails', url: 'https://rubyonrails.org/', color: '#5c0102' },
  { name: 'WordPress', url: 'https://wordpress.org/', color: '#464646' },
  { name: 'Figma', url: 'https://www.figma.com/', color: '#A990C8' },
  { name: 'Docker', url: 'https://www.docker.com', color: '#2497ED' },
  { name: 'Swift', url: 'https://swift.org', color: '#F05138' },
  { name: 'AWS', url: 'https://aws.amazon.com', color: '#F89A1D' },
];

export default function AboutPage() {
  return (
    <>
      <h1>About</h1>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 border-t border-faint-gray pt-8">
        <div className="md:col-span-2">
          <p>
            I&apos;m a frontend engineer with over 15 years of experience
            building web experiences. I&apos;m currently working as a full-time
            engineering leader in New York City. Aside from my current work,
            I&apos;ve previously held positions with Justworks, Two Sigma IQ,
            The University of North Carolina at Chapel Hill, IGN Entertainment,
            Sideways NYC, and Pave.
          </p>

          <p>
            I&apos;ve been fortunate to work in a field that I&apos;m passionate
            about and is never boring. Since I got my start building web apps as
            a teenager in the 1990s, not a week goes by where I don&apos;t get
            the chance to learn something new. I often spend my free time
            reading industry related books or working on personal programming
            projects.
          </p>

          <p>
            <em>I am currently accepting new work.</em>
          </p>

          <h2>My tools</h2>

          <ul className="icon-list">
            {tools.map((tool) => (
              <li key={tool.name}>
                <a
                  href={tool.url}
                  style={{ backgroundColor: tool.color }}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {tool.name}
                </a>
              </li>
            ))}
          </ul>

          <div className="mt-8 hidden md:block">
            <h2>Colophon</h2>

            <p>
              This site was designed and engineered on a{' '}
              <a href="http://www.apple.com/macbook-pro/">MacBook Pro</a> using{' '}
              <a href="https://code.visualstudio.com/">Visual Studio Code</a>{' '}
              for coding.
            </p>

            <p>
              Body text is set in{' '}
              <a href="https://typekit.com/fonts/franklin-gothic-urw">
                Franklin Gothic URW
              </a>{' '}
              served by <a href="http://typekit.com/">Typekit</a>.
            </p>

            <p>
              Pages on this site are generated by{' '}
              <a href="https://nextjs.org/">Next.js</a> and hosted on{' '}
              <a href="https://pages.cloudflare.com/">Cloudflare Pages</a>.
            </p>
          </div>
        </div>

        <div>
          <img
            src="/img/mugshot.jpg"
            alt="Chris drinking tea"
            className="w-full rounded mb-4"
          />

          <div
            className="bg-cover bg-center rounded overflow-hidden"
            style={{ backgroundImage: "url('/img/map.jpg')" }}
          >
            <div className="bg-white/95 p-4 m-4 rounded">
              <p className="mb-2">
                <span className="inline-block w-6">&#9993;</span>
                <a href="mailto:chris@chrisltd.com">chris@chrisltd.com</a>
              </p>
              <p className="mb-2">
                <span className="inline-block w-6">&#9742;</span>
                (917) 727-3545
              </p>
              <p className="mb-0">
                <span className="inline-block w-6">&#9906;</span>
                New York City
              </p>
            </div>
          </div>

          <h2>Contact me</h2>
          <form
            className="wufoo"
            encType="multipart/form-data"
            method="post"
            action="https://chrisltd.wufoo.com/forms/z7x3k1/#public"
          >
            <label htmlFor="Field17" className="block mb-1 font-bold">
              Name<span className="text-orange">*</span>
            </label>
            <input
              id="Field17"
              name="Field17"
              type="text"
              className="text-input"
              maxLength={255}
              required
            />

            <label htmlFor="Field11" className="block mb-1 font-bold">
              Email<span className="text-orange">*</span>
            </label>
            <input
              id="Field11"
              name="Field11"
              type="email"
              className="text-input"
              maxLength={255}
              required
            />

            <label htmlFor="Field15" className="block mb-1 font-bold">
              Message<span className="text-orange">*</span>
            </label>
            <textarea
              id="Field15"
              name="Field15"
              className="text-input"
              required
            />

            <button type="submit" className="btn">
              Submit
            </button>

            <div className="hidden">
              <label htmlFor="comment">Do Not Fill This Out</label>
              <textarea
                name="comment"
                id="comment"
                rows={1}
                cols={1}
                autoComplete="off"
              />
              <input
                type="hidden"
                id="idstamp"
                name="idstamp"
                value="dLWXT1kem80XJKLSKrzpoGu7kVwlvqMG0dQu0PI/+Y8="
                autoComplete="off"
              />
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
