import React from "react"
import Layout from "../components/Layout"
import Seo from "../components/Seo"

const tools = [
  { name: "HTML5", url: "https://en.wikipedia.org/wiki/HTML5", color: "#df4e28" },
  { name: "TypeScript", url: "https://www.typescriptlang.org/", color: "#3178c6" },
  { name: "React", url: "https://reactjs.org/", color: "#292929" },
  { name: "Next.js", url: "https://nextjs.org/", color: "#171717" },
  { name: "Tailwind CSS", url: "https://tailwindcss.com/", color: "#00a6f4" },
  { name: "Git", url: "https://git-scm.com/", color: "#e95235" },
  { name: "Rails", url: "https://rubyonrails.org/", color: "#5c0102" },
  { name: "WordPress", url: "https://wordpress.org/", color: "#464646" },
  { name: "Figma", url: "https://www.figma.com/", color: "#A990C8" },
  { name: "Docker", url: "https://www.docker.com", color: "#2497ED" },
  { name: "Swift", url: "https://swift.org", color: "#F05138" },
  { name: "AWS", url: "https://aws.amazon.com", color: "#F89A1D" },
]

const AboutPage = () => {
  return (
    <Layout pageClass="about">
      <h1>About</h1>

      <div className="grid-layout border-t border-gray-200 pt-8">
        <div className="col-2-3">
          <p className="mb-4">
            I'm a frontend engineer with over 15 years of experience building web experiences. I'm currently working as a full-time engineering leader in New York City. Aside from my current work, I've previously held positions with Justworks, Two Sigma IQ, The University of North Carolina at Chapel Hill, IGN Entertainment, Sideways NYC, and Pave.
          </p>

          <p className="mb-4">
            I've been fortunate to work in a field that I'm passionate about and is never boring. Since I got my start building web apps as a teenager in the 1990s, not a week goes by where I don't get the chance to learn something new. I often spend my free time reading industry related books or working on personal programming projects.
          </p>

          <p className="mb-8 italic">I am currently accepting new work.</p>

          <h2>My tools</h2>

          <div className="icon-list mb-8">
            {tools.map((tool) => (
              <a
                key={tool.name}
                href={tool.url}
                style={{ backgroundColor: tool.color }}
                className="hover:opacity-80"
              >
                {tool.name}
              </a>
            ))}
          </div>

          <div className="hidden md:block">
            <h2 id="colophon">Colophon</h2>

            <p className="mb-4">
              This site was designed and engineered on a{" "}
              <a href="http://www.apple.com/macbook-pro/">MacBook Pro</a> using{" "}
              <a href="https://code.visualstudio.com/">Visual Studio Code</a> for coding,{" "}
              <a href="http://webpack.js.org/">Webpack</a> for compiling{" "}
              <a href="http://sass-lang.com/">SASS</a> and minifying JavaScript, plus the{" "}
              <a href="http://www.adobe.com/products/creativesuite.html">Adobe Creative Suite</a>{" "}
              for creating design assets.
            </p>

            <p className="mb-4">
              Body text is set in{" "}
              <a href="https://typekit.com/fonts/franklin-gothic-urw">Franklin Gothic URW</a>{" "}
              served by <a href="http://typekit.com/">Typekit</a>. Icons on the site are from{" "}
              <a href="http://symbolset.com/">Symbolset's</a> collection of symbol fonts. The map image on this page is from{" "}
              <a href="http://maps.stamen.com/watercolor/#13/40.7767/-73.9493">Stamen Design</a>. The contact form is by{" "}
              <a href="http://www.wufoo.com/">Wufoo</a> for protection from spam.
            </p>

            <p>
              Pages on this site are generated by <a href="https://www.gatsbyjs.com/">Gatsby</a> and served by{" "}
              <a href="http://httpd.apache.org/">Apache</a> running on a{" "}
              <a href="https://m.do.co/c/ff20142d018a">Digital Ocean</a> server.
            </p>
          </div>
        </div>

        <div className="col-1-3">
          <h2 className="sr-only">Chris Johnson</h2>

          <p>
            <img
              src="/img/mugshot.jpg"
              alt="Chris drinking tea"
              className="w-full rounded-lg shadow-md"
            />
          </p>

          <div className="contact-map my-6">
            <div className="contact-map-box">
              <p className="flex items-center gap-2 mb-2">
                <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <a href="mailto:Chris@ChrisLTD.com">Chris@ChrisLTD.com</a>
              </p>
              <p className="flex items-center gap-2 mb-2">
                <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                </svg>
                <span>(917) 727-3545</span>
              </p>
              <p className="flex items-center gap-2">
                <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                <span>New York City</span>
              </p>
            </div>
          </div>

          <h2>Contact me</h2>

          <form
            className="contact-form space-y-4"
            action="https://chrisltd.wufoo.com/forms/z7x3k1/#public"
            method="post"
            encType="multipart/form-data"
          >
            <div>
              <label htmlFor="Field17">
                Name<span className="text-primary">*</span>
              </label>
              <input
                id="Field17"
                name="Field17"
                type="text"
                maxLength="255"
                required
              />
            </div>

            <div>
              <label htmlFor="Field11">
                Email<span className="text-primary">*</span>
              </label>
              <input
                id="Field11"
                name="Field11"
                type="email"
                maxLength="255"
                required
              />
            </div>

            <div>
              <label htmlFor="Field15">
                Message<span className="text-primary">*</span>
              </label>
              <textarea id="Field15" name="Field15" required />
            </div>

            <button type="submit" className="btn">
              Submit
            </button>

            {/* Honeypot */}
            <div className="sr-only" aria-hidden="true">
              <label htmlFor="comment">Do Not Fill This Out</label>
              <textarea name="comment" id="comment" rows="1" cols="1" autoComplete="off" />
              <input
                type="hidden"
                id="idstamp"
                name="idstamp"
                value="dLWXT1kem80XJKLSKrzpoGu7kVwlvqMG0dQu0PI/+Y8="
                autoComplete="off"
              />
            </div>
          </form>
        </div>
      </div>
    </Layout>
  )
}

export const Head = () => <Seo title="About" />

export default AboutPage
